import cynest

cynest.RegisterNeuron("testmodel")
n = cynest.Create("testmodel")
#n = cynest.Create("iaf_psc_delta")

cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.SetStatus(n, [{"p1":2.1}])
cynest.SetStatus(n, [{"p1":2.2}])
cynest.SetStatus(n, [{"p1":2.3}])
cynest.SetStatus(n, [{"p1":2.4}])
#cynest.SetStatus(n, [{"V_reset":-200.1}])
#cynest.SetStatus(n, [{"V_reset":-200.1}])
#cynest.SetStatus(n, [{"V_reset":-200.1}])
#cynest.SetStatus(n, [{"V_reset":-200.1}])
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
cynest.GetStatus(n)
